//! Style types: [`Style`], [`TextStyle`], [`ResolvedStyle`], [`StateFlags`],
//! and the [`StyleResolver`] that merges layered styles into a [`ResolvedStyle`].
//!
//! ## `merge` semantics
//!
//! `merge(base, next)` walks every `Option<_>` field of `base` and replaces
//! it with `next`'s value **only when `next` has `Some`**. The last layer
//! with a `Some` value wins. This is a top-of-stack "override on top"
//! merge, *not* a union.
//!
//! The 30+ `Option<_>` fields all follow the same pattern, so the merge
//! is generated by a single macro invocation — adding a field to `Style`
//! is a one-line change at the single `merge_style_fields!` call site.

use crate::{
    Align, Color, Display, Edge, GridPlacement, GridTrack, Length, Overflow, Paint, Position,
};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DefaultStyleMode {
    /// Full browser-like baseline (Block display, opacity 1.0).
    Full,
    /// Just the structural default (Block display).
    Minimal,
    /// No defaults at all.
    Reset,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct StateFlags(u16);

impl StateFlags {
    pub const EMPTY: Self = Self(0);
    pub const HOVER: Self = Self(1 << 0);
    pub const FOCUS: Self = Self(1 << 1);
    pub const ACTIVE: Self = Self(1 << 2);
    pub const DISABLED: Self = Self(1 << 3);
    pub const CHECKED: Self = Self(1 << 4);
    pub const OPEN: Self = Self(1 << 5);
    pub const SELECTED: Self = Self(1 << 6);
    pub const INVALID: Self = Self(1 << 7);

    pub const fn contains(self, flag: Self) -> bool {
        self.0 & flag.0 == flag.0
    }

    pub const fn bits(self) -> u16 {
        self.0
    }

    pub const fn is_empty(self) -> bool {
        self.0 == 0
    }
}

impl std::ops::BitOr for StateFlags {
    type Output = Self;
    fn bitor(self, rhs: Self) -> Self::Output {
        Self(self.0 | rhs.0)
    }
}

impl std::ops::BitOrAssign for StateFlags {
    fn bitor_assign(&mut self, rhs: Self) {
        self.0 |= rhs.0;
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum FontWeight {
    Thin,
    ExtraLight,
    Light,
    Normal,
    Medium,
    Semibold,
    Bold,
    ExtraBold,
    Black,
    Number(u16),
}

impl Default for FontWeight {
    fn default() -> Self {
        FontWeight::Normal
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum FontStyle {
    Normal,
    Italic,
    Oblique,
}

impl Default for FontStyle {
    fn default() -> Self {
        FontStyle::Normal
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub enum FontStretch {
    Condensed,
    Normal,
    Expanded,
    Percent(f32),
}

impl Default for FontStretch {
    fn default() -> Self {
        FontStretch::Normal
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct TextStyle {
    pub family: Vec<String>,
    pub size: Length,
    pub weight: FontWeight,
    pub style: FontStyle,
    pub stretch: FontStretch,
    /// Text fill color. Use [`Color::DEFAULT`] to mean "resolve from theme"
    /// at paint time — this is the default and is theme-aware.
    pub color: Color,
}

impl Default for TextStyle {
    fn default() -> Self {
        Self {
            family: vec!["system-ui".to_string()],
            size: Length::Px(14.0),
            weight: FontWeight::Normal,
            style: FontStyle::Normal,
            stretch: FontStretch::Normal,
            // Bug fix 1.5: previously hardcoded black, which was invisible on
            // dark themes. Color::DEFAULT is the "resolve at paint time from
            // the active theme" sentinel.
            color: Color::DEFAULT,
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum Background {
    Paint(Paint),
}

impl Default for Background {
    fn default() -> Self {
        Background::Paint(Paint::Solid(Color::DEFAULT))
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Border {
    pub color: Color,
    pub width: f32,
}

impl Default for Border {
    fn default() -> Self {
        Self {
            color: Color::DEFAULT,
            width: 1.0,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Radius {
    pub top_left: f32,
    pub top_right: f32,
    pub bottom_right: f32,
    pub bottom_left: f32,
}

impl Radius {
    pub const fn all(value: f32) -> Self {
        Self {
            top_left: value,
            top_right: value,
            bottom_right: value,
            bottom_left: value,
        }
    }
}

impl Default for Radius {
    fn default() -> Self {
        Self::all(0.0)
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Shadow {
    pub color: Color,
    pub offset_x: f32,
    pub offset_y: f32,
    pub blur: f32,
    pub spread: f32,
}

impl Default for Shadow {
    fn default() -> Self {
        Self {
            color: Color::DEFAULT,
            offset_x: 0.0,
            offset_y: 0.0,
            blur: 0.0,
            spread: 0.0,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Transform {
    pub translate_x: f32,
    pub translate_y: f32,
    pub scale_x: f32,
    pub scale_y: f32,
    pub rotate_radians: f32,
}

impl Default for Transform {
    fn default() -> Self {
        Self {
            translate_x: 0.0,
            translate_y: 0.0,
            scale_x: 1.0,
            scale_y: 1.0,
            rotate_radians: 0.0,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CursorIcon {
    Default,
    Pointer,
    Text,
    ResizeHorizontal,
    ResizeVertical,
}

impl Default for CursorIcon {
    fn default() -> Self {
        CursorIcon::Default
    }
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct Style {
    pub display: Option<Display>,
    pub position: Option<Position>,
    pub width: Option<Length>,
    pub height: Option<Length>,
    pub min_width: Option<Length>,
    pub max_width: Option<Length>,
    pub min_height: Option<Length>,
    pub max_height: Option<Length>,
    pub margin: Option<Edge<Length>>,
    pub padding: Option<Edge<Length>>,
    pub gap: Option<Length>,
    pub align_items: Option<Align>,
    pub align_self: Option<Align>,
    pub align_content: Option<Align>,
    pub justify_content: Option<crate::Justify>,
    pub flex_direction: Option<crate::FlexDirection>,
    pub flex_wrap: Option<crate::FlexWrap>,
    pub flex_grow: Option<f32>,
    pub flex_shrink: Option<f32>,
    pub flex_basis: Option<Length>,
    pub aspect_ratio: Option<f32>,
    pub inset: Option<Edge<Length>>,
    pub overflow_x: Option<Overflow>,
    pub overflow_y: Option<Overflow>,
    pub grid_template_columns: Option<Vec<GridTrack>>,
    pub grid_template_rows: Option<Vec<GridTrack>>,
    pub grid_column: Option<GridPlacement>,
    pub grid_row: Option<GridPlacement>,
    pub background: Option<Background>,
    pub border: Option<Border>,
    pub radius: Option<Radius>,
    pub shadow: Option<Vec<Shadow>>,
    pub opacity: Option<f32>,
    pub transform: Option<Transform>,
    pub z_index: Option<i32>,
    pub text: Option<TextStyle>,
    pub cursor: Option<CursorIcon>,
}

impl Style {
    pub fn new() -> Self {
        Self::default()
    }

    pub const fn display(mut self, value: Display) -> Self {
        self.display = Some(value);
        self
    }

    pub fn width(mut self, value: impl Into<Length>) -> Self {
        self.width = Some(value.into());
        self
    }

    pub fn height(mut self, value: impl Into<Length>) -> Self {
        self.height = Some(value.into());
        self
    }

    pub const fn opacity(mut self, value: f32) -> Self {
        self.opacity = Some(value);
        self
    }

    pub const fn z_index(mut self, value: i32) -> Self {
        self.z_index = Some(value);
        self
    }

    pub fn padding(mut self, value: impl Into<Length>) -> Self {
        let len = value.into();
        self.padding = Some(Edge::all(len));
        self
    }

    pub fn padding_edge(mut self, value: Edge<Length>) -> Self {
        self.padding = Some(value);
        self
    }

    pub fn font_weight(mut self, value: FontWeight) -> Self {
        let mut text = self.text.unwrap_or_default();
        text.weight = value;
        self.text = Some(text);
        self
    }

    pub fn background(mut self, value: Color) -> Self {
        self.background = Some(Background::Paint(Paint::Solid(value)));
        self
    }

    /// Returns `self` with `next`'s `Some` fields overriding `self`'s. Layers
    /// merge top‑down: the last `Some` for a field wins.
    pub fn merge_over(mut self, next: Style) -> Self {
        merge(&mut self, &next);
        self
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct ResolvedStyle {
    pub display: Display,
    pub position: Position,
    pub opacity: f32,
    pub z_index: i32,
    pub text: TextStyle,
    pub transform: Transform,
}

pub struct StyleResolver {
    mode: DefaultStyleMode,
}

impl StyleResolver {
    pub const fn new(mode: DefaultStyleMode) -> Self {
        Self { mode }
    }

    pub fn resolve_layers<I>(&self, layers: I) -> ResolvedStyle
    where
        I: IntoIterator<Item = Style>,
    {
        let mut merged = self.base_style();
        for layer in layers {
            merge(&mut merged, &layer);
        }
        ResolvedStyle {
            display: merged.display.unwrap_or(Display::Block),
            position: merged.position.unwrap_or(Position::Relative),
            opacity: merged.opacity.unwrap_or(1.0),
            z_index: merged.z_index.unwrap_or(0),
            text: merged.text.unwrap_or_default(),
            transform: merged.transform.unwrap_or_default(),
        }
    }

    fn base_style(&self) -> Style {
        match self.mode {
            DefaultStyleMode::Full => Style::default().display(Display::Block).opacity(1.0),
            DefaultStyleMode::Minimal => Style::default().display(Display::Block),
            DefaultStyleMode::Reset => Style::default(),
        }
    }
}

/// Generate the per-field "if `next.X` is `Some`, copy it into `base`"
/// merge body. The field list is co-located with this single call site
/// so adding a new field to `Style` is a one-line change here and one
/// new line in the struct.
macro_rules! merge_style_fields {
    ($base:ident, $next:ident) => {
        if $next.display.is_some() { $base.display = $next.display.clone(); }
        if $next.position.is_some() { $base.position = $next.position.clone(); }
        if $next.width.is_some() { $base.width = $next.width.clone(); }
        if $next.height.is_some() { $base.height = $next.height.clone(); }
        if $next.min_width.is_some() { $base.min_width = $next.min_width.clone(); }
        if $next.max_width.is_some() { $base.max_width = $next.max_width.clone(); }
        if $next.min_height.is_some() { $base.min_height = $next.min_height.clone(); }
        if $next.max_height.is_some() { $base.max_height = $next.max_height.clone(); }
        if $next.margin.is_some() { $base.margin = $next.margin.clone(); }
        if $next.padding.is_some() { $base.padding = $next.padding.clone(); }
        if $next.gap.is_some() { $base.gap = $next.gap.clone(); }
        if $next.align_items.is_some() { $base.align_items = $next.align_items.clone(); }
        if $next.align_self.is_some() { $base.align_self = $next.align_self.clone(); }
        if $next.align_content.is_some() { $base.align_content = $next.align_content.clone(); }
        if $next.justify_content.is_some() { $base.justify_content = $next.justify_content.clone(); }
        if $next.flex_direction.is_some() { $base.flex_direction = $next.flex_direction.clone(); }
        if $next.flex_wrap.is_some() { $base.flex_wrap = $next.flex_wrap.clone(); }
        if $next.flex_grow.is_some() { $base.flex_grow = $next.flex_grow.clone(); }
        if $next.flex_shrink.is_some() { $base.flex_shrink = $next.flex_shrink.clone(); }
        if $next.flex_basis.is_some() { $base.flex_basis = $next.flex_basis.clone(); }
        if $next.aspect_ratio.is_some() { $base.aspect_ratio = $next.aspect_ratio.clone(); }
        if $next.inset.is_some() { $base.inset = $next.inset.clone(); }
        if $next.overflow_x.is_some() { $base.overflow_x = $next.overflow_x.clone(); }
        if $next.overflow_y.is_some() { $base.overflow_y = $next.overflow_y.clone(); }
        if $next.grid_template_columns.is_some() { $base.grid_template_columns = $next.grid_template_columns.clone(); }
        if $next.grid_template_rows.is_some() { $base.grid_template_rows = $next.grid_template_rows.clone(); }
        if $next.grid_column.is_some() { $base.grid_column = $next.grid_column.clone(); }
        if $next.grid_row.is_some() { $base.grid_row = $next.grid_row.clone(); }
        if $next.background.is_some() { $base.background = $next.background.clone(); }
        if $next.border.is_some() { $base.border = $next.border.clone(); }
        if $next.radius.is_some() { $base.radius = $next.radius.clone(); }
        if $next.shadow.is_some() { $base.shadow = $next.shadow.clone(); }
        if $next.opacity.is_some() { $base.opacity = $next.opacity.clone(); }
        if $next.transform.is_some() { $base.transform = $next.transform.clone(); }
        if $next.z_index.is_some() { $base.z_index = $next.z_index.clone(); }
        if $next.text.is_some() { $base.text = $next.text.clone(); }
        if $next.cursor.is_some() { $base.cursor = $next.cursor.clone(); }
    };
}

fn merge(base: &mut Style, next: &Style) {
    merge_style_fields!(base, next);
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Color;

    #[test]
    fn text_style_default_color_is_theme_sentinel() {
        // Bug fix 1.5: hardcoded black was invisible on dark themes.
        let s = TextStyle::default();
        assert!(s.color.is_default(), "default text color must be the theme sentinel");
    }

    #[test]
    fn merge_overrides_only_some_fields() {
        let base = Style::default().width(10.0).height(20.0);
        let next = Style::default().width(99.0); // height stays 20.0
        let merged = base.merge_over(next);
        assert_eq!(merged.width, Some(Length::Px(99.0)));
        assert_eq!(merged.height, Some(Length::Px(20.0)));
    }

    #[test]
    fn merge_later_layer_wins_on_some() {
        let a = Style::default().width(10.0);
        let b = Style::default().width(20.0).height(30.0);
        let c = Style::default().width(40.0);
        let merged = a.merge_over(b).merge_over(c);
        assert_eq!(merged.width, Some(Length::Px(40.0))); // c wins
        assert_eq!(merged.height, Some(Length::Px(30.0))); // b only
    }

    #[test]
    fn merge_with_none_keeps_base() {
        let base = Style::default()
            .width(10.0)
            .height(20.0)
            .opacity(0.5);
        let next = Style::default(); // all None
        let merged = base.merge_over(next);
        assert_eq!(merged.width, Some(Length::Px(10.0)));
        assert_eq!(merged.height, Some(Length::Px(20.0)));
        assert_eq!(merged.opacity, Some(0.5));
    }

    #[test]
    fn merge_is_idempotent_when_next_is_empty() {
        let base = Style::default().width(10.0).height(20.0).opacity(0.5);
        let next = Style::default();
        let merged_once = base.clone().merge_over(next.clone());
        let merged_twice = merged_once.clone().merge_over(next);
        assert_eq!(merged_once, merged_twice);
    }

    #[test]
    fn resolve_layers_uses_defaults_for_missing_fields() {
        let resolver = StyleResolver::new(DefaultStyleMode::Full);
        let resolved = resolver.resolve_layers(std::iter::empty());
        assert_eq!(resolved.display, Display::Block);
        assert_eq!(resolved.opacity, 1.0);
        assert_eq!(resolved.z_index, 0);
        assert!(resolved.text.color.is_default());
    }

    #[test]
    fn state_flags_bitor_assign() {
        let mut f = StateFlags::HOVER;
        f |= StateFlags::FOCUS;
        assert!(f.contains(StateFlags::HOVER));
        assert!(f.contains(StateFlags::FOCUS));
        assert!(!f.contains(StateFlags::ACTIVE));
        assert!(!f.is_empty());
    }
}
